config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  resources :favorites, only: %i(edit create update destroy)
  resources :favorite_organizations, only: %i(index show)
  resources :organizations, only: %i(index show)

  get "/privacy", to: "home#privacy"
  get "/terms", to: "home#terms"

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => "/sidekiq"
    resources :data_files, only: %i(index new create)

    namespace :madmin do
      resources :impersonates do
        post :impersonate, on: :member
        post :stop_impersonating, on: :collection
      end
    end
  end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/favorite_organizations_controller.rb
# frozen_string_literal: true

class FavoriteOrganizationsController < ApplicationController
  include Pagy::Backend

  before_action :authenticate_user!
  # before_action :set_favorite_organization, only: %i(show edit update)
  # before_action :set_favorite, only: %i(show edit update)

  def index
    favorite_organizations = Organization.favorited_by_favoritor current_user
    @favorite_organizations_pagination, @favorite_organizations = pagy favorite_organizations
  end

  def show
    @favorite_organization = Organization.find params[:id]
    @favorite = @favorite_organization.favorited.where(favoritor: current_user).first
  end

  # def edit
  # end

  # def update
  #   if @favorite.update favorite_params
  #     redirect_to @favoritable_organization
  #   end
  # end

  private
    # def set_favorite
    # end

    # def set_favorite_organization
    # end

    def favoritable_organization_params
      params.require(:favorite_params).permit(:notes)
    end
end

app/views/favorite_organizations/_favorite_organization.html.erb
<div class="col">

  <div id="<%= dom_id favorite_organization %>" class="card h-100">
    <div class="card-body">
      <h5 class="card-title"><%= link_to favorite_organization.title, favorite_organization_path(favorite_organization) %></h5>
      <p class="card-text">
        <%= render partial: "organizations/status", locals: { status: favorite_organization.administrative_status.status } %>
        <%= render partial: "organizations/social_reason_code", locals: { code: favorite_organization.primary_social_reason.code, description: nil } %>
        <% if favorite_organization.secondary_social_reason %>
        <%= render partial: "organizations/social_reason_code", locals: { code: favorite_organization.secondary_social_reason.code, description: nil } %>
        <% end %>
        <small>
        <%= favorite_organization.municipality_description %>
        </small>
      </p>
      <p class="card-text">
      <% if favorite_organization.favorite_for_favoritor(current_user).notes.empty? %>
        <%= favorite_organization.reason.truncate_words(20, omission: "...") %>
      <% else %>
        <%= favorite_organization.favorite_for_favoritor(current_user).notes.to_plain_text.truncate_words(20, omission: "...") %>
      <% end %>
      </p>
    </div>

    <div class="card-footer">
      <%= render partial: "favorites/unfavorite_form", locals: { favoritor: current_user, favoritable: favorite_organization } %>
    </div>
  </div>
</div>

app/views/favorite_organizations/_favorite_organizations.html.erb
<%= turbo_frame_tag "favorite_organizations" do %><div class="row row-cols-1 row-cols-lg-2 g-2">
    <% @favorite_organizations.try(:each) do |favorite_organization| %>
        <%= render partial: "favorite_organizations/favorite_organization", locals: { favorite_organization: favorite_organization } %>
    <% end%>

    <%= render partial: "organizations/pagination",
    locals: { pagination: @favorite_organizations_pagination } %>
</div>
<% end%>

app/views/favorite_organizations/index.html.erb
<div class="row align-items-center">
  <div class="col-sm-6">
    <h1>Favorite Organizations</h1>
  </div>
</div>

<hr />

<%= render partial: "favorite_organizations/favorite_organizations",
locals: {
  favorite_organizations: @favorite_organizations,
  pagination: @favorite_organizations_pagination
} %>
<%= console  %>

app/views/favorite_organizations/show.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <%= link_to favorite_organizations_path do %>
        My Favorite Organizations
      <% end %>
    </li>
    <li class="breadcrumb-item active" aria-current="page">
        <%= @favorite_organization.short_title.truncate(30, omission: "...") %>
    </li>
  </ol>
</nav>

<div class="card">
  <div class="card-body">
    <h5 class="card-title"><%= @favorite_organization.title %></h5>
    <h6 class="card-subtitle mb-2 text-muted"><%= @favorite_organization.reason %>e</h6>
  </div>
</div>

<br />

<div class="card p-3">
    <%= turbo_frame_tag dom_id(@favorite) do %>
        <%= link_to edit_favorite_path(@favorite), class: "btn btn-primarybtn btn-primary" do %>
            Edit notes
        <% end %>
        <hr />
        <div class="card-content">
            <% if @favorite.notes.present? %>
            <%= @favorite.notes %>
            <% else %>
            <p>No notes yet.</p>
            <% end %>
        </div>
    <% end %>
</div>