config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  resources :favorites, only: %i(edit create update destroy)
  resources :favorite_organizations, only: %i(index show)
  resources :organizations, only: %i(index show)

  get "/privacy", to: "home#privacy"
  get "/terms", to: "home#terms"

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => "/sidekiq"
    resources :data_files, only: %i(index new create)

    namespace :madmin do
      resources :impersonates do
        post :impersonate, on: :member
        post :stop_impersonating, on: :collection
      end
    end
  end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/favorite.rb
# frozen_string_literal: true

class Favorite < ApplicationRecord
  extend ActsAsFavoritor::FavoriteScopes
  has_rich_text :notes

  belongs_to :favoritable, polymorphic: true
  belongs_to :favoritor, polymorphic: true

  def block!
    update!(blocked: true)
  end
end

app/controllers/favorites_controller.rb
# frozen_string_literal: true

class FavoritesController < ApplicationController
  before_action :set_favoritor, only: %i(create destroy)
  before_action :set_favoritable, only: %i(create destroy)

  def create
    @favoritor.favorite @favoritable
    @favorite = @favoritor.get_favorite @favoritable

    render turbo_stream: turbo_stream.replace(
      "favoritable_#{@favoritable.class.name.downcase.underscore}_#{@favoritable.id}",
      partial: "unfavorite_form",
      locals: { favoritor: @favoritor, favoritable: @favoritable }
    )
  end

  def edit
    @favorite = Favorite.find params[:id]
  end

  def update
    @favorite = Favorite.find params[:id]
    if @favorite.update favorite_params
      redirect_to favorite_organization_path(@favorite.favoritable)
    end
  end

  def destroy
    @favorite = Favorite.find(params[:id]).destroy

    favorite_organizations = Organization.favorited_by_favoritor current_user
    @favorite_organizations_pagination, @favorite_organizations = pagy favorite_organizations

    render turbo_stream: [
      turbo_stream.replace(
      "favoritable_#{@favoritable.class.name.downcase.underscore}_#{@favoritable.id}",
      partial: "favorite_form",
      locals: { favoritor: @favoritor, favoritable: @favoritable }
    ),
    turbo_stream.update(
      "favorite_organizations",
      partial: "favorite_organizations/favorite_organizations",
      locals: {
        favorite_organizations: @favorite_organizations,
        pagination: @favorite_organizations_pagination
      })
    ]
  end

  private
    def set_favoritor
      @favoritor = User.find favorite_params[:favoritor_id]
    end

    def set_favoritable
      favoritable_class = favorite_params[:favoritable_type].classify.constantize
      @favoritable = favoritable_class.find favorite_params[:favoritable_id]
    end

    def favorite_params
      params.require(:favorite)
      .permit(
        :id,
        :favoritor_id,
        :favoritable_id,
        :favoritable_type,
        :notes
      )
    end
end

app/views/favorites/_favorite_form.html.erb
<%= turbo_frame_tag "favoritable_organization_#{favoritable.id}" do %>
    <%= form_with model: Favorite.new do |form| %>
        <%= form.hidden_field :favoritor_id, value: favoritor.id %>
 
        <%= form.hidden_field :favoritable_id, value: favoritable.id %>
        <%= form.hidden_field :favoritable_type, value: favoritable.class %>

        <%= form.button class: "btn -btn-secondary" do %>
            <%= icon "fa-regular", "star", { class:"text-warning" } %>
            Add to favorites
        <% end %>
    <% end %>
<% end %>

app/views/favorites/_form.html.erb
<% if favoritor.favorited? favoritable %>
    <% favorite = favoritor.get_favorite favoritable %>
    <% url = favorite_path(favorite.id) %>
    <% method = :delete %>
    <% submit_icon = icon('fa-solid', 'star', { class:"text-warning"})%>
    <% submit_text = "Remove from favorites" %>
<% else %>
    <% favorite = Favorite.new %>
    <% url = nil %>
    <% method = :post %>
    <% submit_icon = icon('fa-regular', 'star', { class:"text-warning"})%>
    <% submit_text = "Add to favorites" %>
<% end %>

<%= form_with model: favorite, url:, method: do |form| %>
    <%= form.hidden_field :id, value: favorite.id %>

    <%= form.hidden_field :favoritor_id, value: favoritor.id %>

    <%= form.hidden_field :favoritable_id, value: favoritable.id %>
    <%= form.hidden_field :favoritable_type, value: favoritable.class %>

    <%= button_tag type: "submit", class: "btn -btn-secondary" do %>
        <%= submit_icon %>
        <%= submit_text %>
    <% end %>
<% end %>

app/views/favorites/_unfavorite_form.html.erb
<% favorite = favoritor.get_favorite favoritable %>

<%= turbo_frame_tag "favoritable_organization_#{favoritable.id}" do %>
    <%= form_with model: favorite, url: favoritor.get_favorite(favoritable), method: :delete do |form| %>

        <%= form.hidden_field :id, value: favorite.id %>
        <%= form.hidden_field :favoritor_id, value: favoritor.id %>

        <%= form.hidden_field :favoritable_id, value: favoritable.id %>
        <%= form.hidden_field :favoritable_type, value: favoritable.class %>

        <%= form.button class: "btn -btn-primary" do %>
            <%= icon "fa-solid", "star", { class:"text-warning" } %>
            Remove from favorites
        <% end %>
    <% end %>
<% end %>

app/views/favorites/edit.html.erb
<%= turbo_frame_tag dom_id(@favorite) do %>
    <%= form_with model: @favorite do |form| %>
        <div class="mb-3">
        <%= form.label :notes %>
        <%= form.rich_text_area :notes, { style: "height: 20rem;" } %>
        </div>

        <div class="mb-3">
        <%= form.submit "Update notes", class: "btn btn-primarybtn btn-primary" %>
        </div>
    <% end %>
<% end %>