config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  resources :favorites, only: %i(edit create update destroy)
  resources :favorite_organizations, only: %i(index show)
  resources :organizations, only: %i(index show)

  get "/privacy", to: "home#privacy"
  get "/terms", to: "home#terms"

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => "/sidekiq"
    resources :data_files, only: %i(index new create)

    namespace :madmin do
      resources :impersonates do
        post :impersonate, on: :member
        post :stop_impersonating, on: :collection
      end
    end
  end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_footer.html.erb
<footer class="bg-light footer mt-auto py-3">
  <div class="container d-flex justify-content-between mx-auto text-muted">
    <span>&copy; <%= Date.today.year %> Your Company</span>
    <ul class="d-inline float-end list-inline mb-0">
      <li class="list-inline-item mr-3"><%= link_to "Terms", terms_path %></li>
      <li class="list-inline-item mr-3"><%= link_to "Privacy", privacy_path %></li>
    </ul>
  </div>
</footer>

app/views/shared/_head.html.erb
<title><%= Rails.configuration.application_name %></title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" integrity="sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<%= stylesheet_link_tag "application", media: "all", "data-turbo-track": "reload" %>
<%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

app/views/shared/_navbar.html.erb
<% if current_user != true_user %>
  <div class="alert alert-warning text-center">
    You're logged in as <b><%= current_user.name %> (<%= current_user.email %>)</b>
    <%= link_to stop_impersonating_madmin_impersonates_path, method: :post do %><%= icon("fas", "times") %> Logout <% end %>
  </div>
<% end %>

<nav class="navbar navbar-expand-md navbar-light bg-light">
  <div class="container mx-auto">
    <%= link_to Rails.configuration.application_name, root_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarMain" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarMain">
      <ul class="navbar-nav me-auto mt-2 mt-md-0">
      </ul>

      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "What's New", announcements_path, class: "nav-link #{unread_announcements(current_user)}" %>
        </li>
        
        <% if current_user.try(:admin?) %>
        <li class="nav-item">
          <%= link_to "Data Files", data_files_path, class: "nav-link" %>
        </li>
        <% end%>

        <li class="nav-item">
          <%= link_to "Organizations", organizations_path, class: "nav-link" %>
        </li>

        <% if user_signed_in? %>
          <li>
            <hr />
          </li>
          <li class="nav-item">
            <%= link_to "My Favorite Organizations", favorite_organizations_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to notifications_path, class: "nav-link" do %>
              <span><i class="far fa-bell" aria-hidden="true"></i></span>
            <% end %>
          </li>
          <li class="nav-item dropdown">
            <%= link_to "#", id: "navbar-dropdown", class: "nav-link dropdown-toggle", data: { target: "nav-account-dropdown", bs_toggle: "dropdown" }, aria: { haspopup: true, expanded: false } do %>
              <%= image_tag avatar_path(current_user, size: 40), height: 20, width: 20, class: "rounded" %>
            <% end %>
            <div id="nav-account-dropdown" class="dropdown-menu dropdown-menu-end" aria-labelledby="navbar-dropdown">
              <%= link_to "Settings", edit_user_registration_path, class: "dropdown-item" %>
              <% if current_user.admin? && respond_to?(:madmin_root_path) %>
                <div class="dropdown-divider"></div>
                <%= link_to "Admin Area", madmin_root_path, class: "dropdown-item" %>
              <% end %>
              <div class="dropdown-divider"></div>
              <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>

        <% else %>
          <li class="nav-item"><%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Login", new_user_session_path, class: "nav-link" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_notices.html.erb
<% flash.each do |msg_type, message| %>
  <div class="container mt-4 mx-auto">
    <div class="alert <%= bootstrap_class_for(msg_type) %> alert-dismissible fade show" role="alert">
      <%= message %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  </div>
<% end %>