config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  resources :favorites, only: %i(edit create update destroy)
  resources :favorite_organizations, only: %i(index show)
  resources :organizations, only: %i(index show)

  get "/privacy", to: "home#privacy"
  get "/terms", to: "home#terms"

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => "/sidekiq"
    resources :data_files, only: %i(index new create)

    namespace :madmin do
      resources :impersonates do
        post :impersonate, on: :member
        post :stop_impersonating, on: :collection
      end
    end
  end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/data_file.rb
# frozen_string_literal: true

class DataFile < ApplicationRecord
  has_many :organizations
  has_many :social_reasons

  enum :data_category, { organization: "0", social_reason: "1" }

  validates_presence_of :original_filename, :content
end

app/models/organization.rb
# frozen_string_literal: true

class Organization < ApplicationRecord
  extend Pagy::Searchkick
  searchkick word_start: %i(title reason)

  acts_as_favoritable

  belongs_to :data_file
  belongs_to :primary_social_reason, class_name: "SocialReason", foreign_key: "primary_social_reason_id"
  belongs_to :secondary_social_reason, class_name: "SocialReason", foreign_key: "secondary_social_reason_id", required: false
  has_one :administrative_status, class_name: "OrganizationStatus", inverse_of: :organization, dependent: :destroy
  accepts_nested_attributes_for :administrative_status

  validates :national_uid, presence: true, uniqueness: true
  validates_uniqueness_of :siret, allow_blank: true, case_sensitive: false
  validates_presence_of :site_administrator_code,
  :creation_date,
  :title,
  :publication_date,
  :data_update_time

  scope :favorited_by_favoritor, -> (favoritor) { joins(:favorited)
    .where(favorited: { favoritor_type: favoritor.class.name })
    .where(favorited: { favoritor_id: favoritor.id })
  }

  CSV_OPTIONS = {
    force_utf8: true,
    col_sep: ";",
    headers_mapping: {
      id: :national_uid,
      id_ex: :former_uid,
      siret: :siret,
      rup_mi: nil,
      gestion: :site_administrator_code,
      date_creat: :creation_date,
      date_decla: :declaration_date,
      date_publi: :publication_date,
      date_disso: :dissolution_date,
      nature: :kind_code,
      groupement: :grouping,
      titre: :title,
      titre_court: :short_title,
      objet: :reason,
      objet_social1: :social_reason_1,
      objet_social2: :social_reason_2,
      adrs_complement: :additional_address,
      adrs_numvoie: :street_number,
      adrs_repetition: :additional_street_number,
      adrs_typevoie: :street_type,
      adrs_libvoie: :street_name,
      adrs_distrib: :additional_street_name,
      adrs_codeinsee: :insee_address_code,
      adrs_codepostal: :zipcode,
      adrs_libcommune: :municipality_description,
      adrg_declarant: :declarant_family_name,
      adrg_complemid: :manager_address,
      adrg_complemgeo: :manager_additional_address,
      adrg_libvoie: :manager_street_name,
      adrg_distrib: :manager_additional_street_name,
      adrg_codepostal: :manager_zipcode,
      adrg_achemine: :manager_billing_address,
      adrg_pays: :manager_state,
      dir_civilite: :manager_gender,
      siteweb: :web_site,
      publiweb: :web_publication,
      observation: :remark,
      position: :status,
      maj_time: :data_update_time
    }
  }.freeze

  def active?
    administrative_status.active?
  end

  def dissolved?
    administrative_status.dissolved?
  end

  def canceled?
    administrative_status.canceled?
  end

  def search_data
    {
      title:,
      reason:,
      status: administrative_status.status,
      social_reason_ids: [primary_social_reason_id, secondary_social_reason_id]

    }
  end

  def favorite_for_favoritor(favoritor)
    favorited.where(favoritor:).first
  end

  private
    def self.csv_options
      CSV_OPTIONS
    end
end

app/controllers/organizations_controller.rb
# frozen_string_literal: true

class OrganizationsController < ApplicationController
  DEFAULT_SEARCH = "*"
  ITEMS_SIZE = 10

  def index
    search = params[:search].try(:presence) || DEFAULT_SEARCH

    administrative_statuses = []
    OrganizationStatus.statuses.keys.each do |status_key|
      if params[status_key].present?
        administrative_statuses << status_key
      end
    end
    administrative_statuses << "active" if administrative_statuses.empty?


    if params[:social_reason_ids].present? && params[:social_reason_ids].reject(&:blank?).any?
      social_reason_ids = [params[:social_reason_ids].presence].flatten.reject(&:empty?).map(&:to_s)
      social_reason_filters = true
    else
      social_reason_ids = SocialReason.all.map(&:id)
      social_reason_filters = false
    end

    fields = params[:search_by_title_only].present? ? %i(title) : %i(title reason)

    organizations = Organization.pagy_search(
      search,
      fields:,
      misspellings: { edit_distance: 2 },
      where: {
        social_reason_ids:,
        status: administrative_statuses
      }
    )

    @organizations_pagination, @organizations = pagy_searchkick(organizations, items: ITEMS_SIZE)
    @social_reasons = SocialReason.asc_codes
    filters = {}
    filters[:social_reasons_codes] = SocialReason.find(social_reason_ids).map(&:code) if social_reason_filters
    filters[:statuses] = administrative_statuses
    @filters = filters
  end

  def show
    @organization = Organization.find(params[:id])
  end
end

app/helpers/organization_helper.rb
# frozen_string_literal: true

module OrganizationHelper
  def h_status_color(status)
    status_colors = {
        active: "success",
        dissolved: "warning",
        canceled: "danger"
    }
    status_colors[status.to_sym]
  end
end

app/views/organizations/_attribute_list.html.erb
    <hr />

    <dl class="dl-horizontal">
    <% attributes.each do |attribute| %>
      <% if organization.send attribute%>
      <dt><%= attribute.to_s.humanize %>:</dt>
      <dd><%= organization.send attribute %></dd>
      <% end%>
    <% end%>
    </dl>

app/views/organizations/_organization.html.erb
<div class="col">

  <div id="<%= dom_id organization %>" class="card h-100">
    <div class="card-body">
      <h5 class="card-title"><%= link_to organization.title, organization %></h5>
      <p class="card-text">
        <%= render partial: "organizations/status", locals: { status: organization.administrative_status.status } %>
        <%= render partial: "organizations/social_reason_code", locals: { code: organization.primary_social_reason.code, description: nil } %>
        <% if organization.secondary_social_reason %>
        <%= render partial: "organizations/social_reason_code", locals: { code: organization.secondary_social_reason.code, description: nil } %>
        <% end %>
        <small>
        <%= organization.municipality_description %>
        </small>
      </p>
      <p class="card-text">
        <%= organization.reason.truncate_words(20, omission: "...") %>
      </p>
    </div>

    <% if user_signed_in? %>
    <div class="card-footer">
      <% if current_user.favorited? organization %>
      <%= render partial: "favorites/unfavorite_form", locals: { favoritor: current_user, favoritable: organization } %>
      <% else %>
      <%= render partial: "favorites/favorite_form", locals: { favoritor: current_user, favoritable: organization } %>
      <% end %>
    </div>
    <% end %>
  </div>
</div>

app/views/organizations/_pagination.html.erb
<% if pagination.pages > 1 %>
  <div class="container d-flex justify-content-center my-2">
    <%== pagy_bootstrap_nav pagination %>
  </div>
<% end %>

app/views/organizations/_search_form.html.erb
<%= form_with(url: organizations_url, method: :get) do |form| %>
    <%= form.label :search %>
  <div class="input-group mb-3">
    <%= form.search_field :search,
    value: params[:search],
    onsubmit: "this.value=''",
    class: "form-control" %>
    <%= form.submit "Search", class: "btn btn-primary" %>
  </div>

  <div class="mb-3">
    <div class="form-check form-switch">
      <%= form.label :search_by_title_only, class: "form-check-label" %>
      <%= form.check_box :search_by_title_only, { class: "form-check-input" }, true, false %>
    </div>
  </div>

  <div class="mb-3">
    <%= form.label "filter by social reason(s)" %>
    <%= form.collection_select :social_reason_ids,
    @social_reasons,
    :id,
    :code_with_description_label,
    {},
    { multiple: true, class: "form-select" } %>
  </div>


  <%= form.label "filter by status(es)" %>
  <% active_check = if params[:active].present? || (params[:dissolved].nil? && params[:canceled].nil?)
  true
  else
  false
  end %>
  <div class="form-check form-switch">
    <%= form.label :active, class: "form-check-label" %>
    <%= form.check_box :active, { checked: active_check,  class: "form-check-input" }, true, false %>
  </div>

  <% dissolved_check = params[:dissolved].present? ? true : false %>
  <div class="form-check form-switch">
    <%= form.label :dissolved, class: "form-check-label" %>
    <%= form.check_box :dissolved, { checked: dissolved_check, class: "form-check-input" }, true, false %>
  </div>

  <% canceled_check = params[:canceled].present? ? true : false %>
  <div class="form-check form-switch">
    <%= form.label :canceled, class: "form-check-label" %>
    <%= form.check_box :canceled, { checked: canceled_check, class: "form-check-input" }, true, false %>
  </div>
<% end %>

app/views/organizations/_social_reason_code.html.erb
<% text = description.present? ? "#{code} - #{description}" : code %>
<span class="badge rounded-pill bg-secondary"><%= text %></span>

app/views/organizations/_status.html.erb
<span class="badge bg-<%= h_status_color(status) %>"><%= status %></span>

app/views/organizations/index.html.erb
<div class="row align-items-center">
  <div class="col-sm-6">
    <h1>Organizations</h1>
  </div>
</div>

<hr />

<div class="container d-flex justify-content-center my-2">
  <%= render partial: "search_form" %>
</div>

<hr />

<div class="row">
<% unless @filters.empty? %>
<div class="h5">Current filters</div>
<div id="current_filters" class="col mb-4">
  <% @filters[:social_reasons_codes].try(:each) do |social_reason_code| %>
  <%= render partial: "social_reason_code", locals: { code: social_reason_code, description: nil } %>
  <% end %>
  
  <% if @filters[:statuses].present? && @filters[:social_reasons_codes].present? %>
  <br />
  <% end %>

  <% @filters[:statuses].try(:each) do |status| %>
  <%= render partial: "status", locals: { status: status } %>
  <% end %>
</div>
<% end %>

<hr />

<% if params[:search].present? %>
<h2 class="h4">Results for '<strong><%= params[:search] %></strong>'</h2>
<% else %>
<% title_start = @filters[:statuses].count < 3  ? @filters[:statuses].to_sentence.humanize : "All" %>
<h2 class="h4"><%= title_start %> organizations</h2>
<% end %>
</div>

<div class="row row-cols-1 row-cols-lg-2 g-2">
  <%= render @organizations %>
</div>

<%= render partial: "pagination", locals: { pagination: @organizations_pagination } %>

app/views/organizations/show.html.erb
<div class="page-header">
  <%= link_to organizations_path, class: 'btn btn-default' do %>
    All Organizations
  <% end %>
</div>

<div class="px-4 py-2 my-2 text-center">
  <h1 class="display-5 fw-bold"><%= @organization.title %></h1>
  <div class="col-lg-6 mx-auto">
    <p class="lead mb-4"><%= @organization.reason %></p>
    <% if @organization.web_site%>
    <%= link_to "Visit website", @organization.web_site %>
    <% end %>
    <hr /> 

    <p>
    <%= @organization.national_uid %>
    <%= render partial: "status", locals: { status: @organization.administrative_status.status } %>
    </p>

    <%= render partial: "social_reason_code", locals: { code: @organization.primary_social_reason.code, description: @organization.primary_social_reason.description } %>
    <%= render partial: "social_reason_code", locals: { code: @organization.primary_social_reason.code, description: @organization.primary_social_reason.description } %>
    <% if @organization.secondary_social_reason %>
    <%= render partial: "social_reason_code", locals: { code: @organization.secondary_social_reason.code, description: @organization.secondary_social_reason.description } %>
    <% end %>
   
    <hr />

    <dl class="dl-horizontal">
      <dt>Creation date:</dt>
      <dd><%= @organization.creation_date.to_formatted_s %></dd>
      <dt>Publication date:</dt>
      <dd><%= @organization.publication_date %></dd>
      <% if @organization.dissolved? %>
      <dt>Dissolution date:</dt>
      <dd><%= @organization.dissolution_date %></dd>
      <% end %>
    </dl>


    <%= render partial: "attribute_list",
    locals: {
      organization: @organization,
      attributes: %i(
      former_uid
      siret
      site_administrator_code
      kind_code
      grouping)
    } %>

    <hr />
    <%= "#{@organization.street_number} \
    #{@organization.additional_street_number} \
    #{@organization.street_type} \
    #{@organization.street_name} \
    #{@organization.additional_street_name} \
    #{@organization.additional_address}" %>
    <br />
    <%= "#{@organization.zipcode} - \
    #{@organization.municipality_description}" %>

    <hr />
    <%= "#{@organization.manager_address} \
    #{@organization.manager_additional_address} \
    #{@organization.manager_street_name} \
    #{@organization.manager_additional_street_name} \
    #{@organization.additional_address}" %>
    <br />
    <%= "#{@organization.manager_zipcode} - \
    #{@organization.manager_billing_address} \
    #{@organization.manager_state}" %>


    <dl class="dl-horizontal">
      <hr />
      
      <dt>Declarant family name:</dt>
      <dd><%= @organization.declarant_family_name %></dd>
      <dt>Manager gender:</dt>
      <dd><%= @organization.manager_gender %></dd>
      <dt>Insee address code:</dt>
      <dd><%= @organization.insee_address_code %></dd>
    
      <hr />

      <dt>Data update time:</dt>
      <dd><%= @organization.data_update_time.to_formatted_s :long %></dd>
      <dt>Organization data file:</dt>
      <dd><%= @organization.data_file.original_filename %></dd>
    </dl>
  </div>
</div>